#!/bin/env bash

#SBATCH --job-name=sm11
#SBATCH --mem-per-cpu=40G
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=1
#SBATCH --partition=gpu
#SBATCH --gres=gpu
#SBATCH --output=/home/ubelix/artorg/lejeune/runs/logs/%x.out

simg=$HOME/ksptrack-ubelix.simg
pyversion=my-3.7

export OMP_NUM_THREADS=1

args="--cuda --out-root $HOME/runs/siamese_dec --in-root $HOME/data/medical-labeling --train-dirs 52 53 54 --run-dirs Dataset52 Dataset53 Dataset54"

singularity exec --nv $simg /bin/bash -c "source $HOME/.bashrc && pyenv activate $pyversion && cd $HOME/Documents/software/ksptrack/ksptrack/siamese && python train_all_type.py $args"

